apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: pgi-lagre-inntekt-popp
  namespace: pensjonopptjening
  labels:
    team: pensjonopptjening
spec:
  image: {{ image }}
  port: 8080
  secureLogs:
    enabled: true
  prometheus:
    enabled: true
    path: /metrics
  azure:
    application:
      enabled: true
      tenant: trygdeetaten.no
  envFrom:
    - secret: pgi-lagre-inntekt-popp-secrets
  kafka:
    pool: nav-dev
  accessPolicy:
    outbound:
      external:
        - host: pensjon-popp.dev-fss-pub.nais.io
  liveness:
    path: isAlive
    initialDelay: 5
  readiness:
    path: isReady
    initialDelay: 5
  replicas:
    min: 1
    max: 1
  env:
    - name: APP_TEAM
      value: pensjonopptjening
