apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: pgi-lagre-inntekt-popp
  namespace: pensjonsamhandling
  labels:
    team: pensjonsamhandling
spec:
  image: {{ image }}
  team: pensjonsamhandling
  port: 8080
  azure:
    application:
      enabled: true
  envFrom:
    - secret: pgi-lagre-inntekt-popp-secrets
  kafka:
    pool: nav-prod
  accessPolicy:
    outbound:
      external:
        - host: pensjon-popp.prod-fss-pub.nais.io
  liveness:
    path: isAlive
    initialDelay: 5
  readiness:
    path: isReady
    initialDelay: 5
  replicas:
    min: 1
    max: 1
  env:
    - name: APP_TEAM
      value: pensjonsamhandling