apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: pgi-lagre-inntekt-popp
  namespace: pensjonopptjening
  labels:
    team: pensjonopptjening
spec:
  image: {{ image }}
  port: 8080
  secureLogs:
    enabled: true
  prometheus:
    enabled: true
    path: /metrics
  azure:
    application:
      enabled: true
  envFrom:
    - secret: pgi-lagre-inntekt-popp-secrets
  kafka:
    pool: nav-prod
  accessPolicy:
    outbound:
      external:
        - host: pensjon-popp.prod-fss-pub.nais.io
  liveness:
    path: /actuator/health/liveness
    port: 8080
    initialDelay: 50
  readiness:
    path: /actuator/health/readiness
    port: 8080
    initialDelay: 50
  prometheus:
    enabled: true
    path: /actuator/prometheus
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
  replicas:
    min: 1
    max: 1
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: prod-gcp
    - name: APP_TEAM
      value: pensjonopptjening
