apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: pgi-lagre-inntekt-popp
  namespace: pensjonopptjening
  labels:
    team: pensjonopptjening
spec:
  image: {{ image }}
  port: 8080
  azure:
    application:
      enabled: true
      tenant: trygdeetaten.no
  envFrom:
    - secret: pgi-lagre-inntekt-popp-secrets
  kafka:
    pool: nav-dev
  accessPolicy:
    outbound:
      rules:
        - application: logging
          namespace: nais-system
      external:
        - host: pensjon-popp.dev-fss-pub.nais.io
  liveness:
    path: /actuator/health/liveness
    port: 8080
    initialDelay: 50
  readiness:
    path: /actuator/health/readiness
    port: 8080
    initialDelay: 50
  prometheus:
    enabled: true
    path: /actuator/prometheus
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
    logging:
      destinations:
        - id: loki
        - id: elastic
  replicas:
    min: 1
    max: 1
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: dev-gcp
    - name: APP_TEAM
      value: pensjonopptjening
